name: Greetings
on:
  [pull_request_target, issues]

jobs:
  greet:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for raising an issue! We appreciate your contribution."
          pr-message: "Welcome to the project! Thank you for your first pull request."
